repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: shellcheck
        files: \.sh$
        args:
          - --severity=warning
  - repo: local
    hooks:
      - id: regen-bootstrap
        name: regenerate bootstrap.sh
        language: script
        entry: ./create_bootstrap.sh
        files: ^setup/.*\.sh$
        pass_filenames: false
