# ~/.tmuxinator/libstatus.yml
# you can make as many windows as you wish...

project_name: libstatus
project_root: ~/dev/rails/libstatus
pre:
  - export RBENV_DIR=
windows:
  - shell: git s
  - editor: vim
  - console: ./script/console
  - guard: guard
